version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=alerts
    ports:
      - '5432:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  picord:
    restart: always
    container_name: picord
    build:
      context: ./
    image: picord
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alerts
      TOKEN: 111
      CHANNELID: 111
    links:
      - db